In [8]:
#Import Dependencies
import pandas as pd

In [9]:
#Reference the fileName of the csv file
file_to_load="Resources/crime_incident_data2017.csv"

In [10]:
#read csv file
crime_data_df=pd.read_csv(file_to_load)
crime_data_df.head()

,Address,Case Number,Crime Against,Neighborhood,Number of Records,Occur Date,Occur Month Year,Occur Time,Offense Category,Offense Count,Offense Type,Open Data Lat,Open Data Lon,Open Data X,Open Data Y,Report Date,Report Month Year
0,NaN,17-X4762181,Person,NaN,1,1/1/96,1/1/96,800,Sex Offenses,1,Rape,NaN,NaN,NaN,NaN,1/26/17,1/1/17
1,NaN,17-X4757824,Property,Centennial,1,1/20/00,1/1/00,1615,Fraud Offenses,1,Identity Theft,NaN,NaN,NaN,NaN,1/20/17,1/1/17
2,200 BLOCK OF SE 78TH AVE,17-900367,Property,Montavilla,1,12/1/03,12/1/03,800,Fraud Offenses,1,False Pretenses/Swindle/Confidence Game,45.5207,-122.583,7668150.0,682825.0,1/9/17,1/1/17
3,NaN,17-X4748982,Property,Southwest Hills,1,1/1/10,1/1/10,0,Fraud Offenses,1,Identity Theft,NaN,NaN,NaN,NaN,1/5/17,1/1/17
4,NaN,17-X4748982,Property,Southwest Hills,1,1/1/10,1/1/10,0,Larceny Offenses,1,All Other Larceny,NaN,NaN,NaN,NaN,1/5/17,1/1/17
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
41027,8800 BLOCK OF NE SANDY BLVD,17-285386,Society,Sumner,1,8/31/17,8/1/17,535,Drug/Narcotic Offenses,1,Drug/Narcotic Violations,45.5554,-122.571,7671560.0,695399.0,8/31/17,8/1/17
41028,9700 BLOCK OF SE STARK ST,17-286082,Society,Hazelwood,1,8/31/17,8/1/17,1619,Prostitution Offenses,1,Prostitution,45.5191,-122.563,7673292.0,682101.0,8/31/17,8/1/17
41029,9700 BLOCK OF SE STARK ST,17-286413,Society,Hazelwood,1,8/31/17,8/1/17,1959,Prostitution Offenses,1,Prostitution,45.5191,-122.563,7673292.0,682101.0,8/31/17,8/1/17
41030,UNKNOWN ADDRESS,17-286445,Society,NaN,1,8/31/17,8/1/17,2021,Prostitution Offenses,1,Prostitution,NaN,NaN,NaN,NaN,8/31/17,8/1/17
41031,8000 BLOCK OF SE POWELL BLVD,17-286659,Society,Foster-Powell,1,8/31/17,8/1/17,2354,Weapon Law Violations,1,Weapons Law Violations,45.4974,-122.580,7668725.0,674298.0,8/31/17,8/1/17

In [11]:
# Determine if there are any missing values in the crime data.
crime_data_df.count()

Address              37365
Case Number          41032
Crime Against        41032
Neighborhood         39712
Number of Records    41032
Occur Date           41032
Occur Month Year     41032
Occur Time           41032
Offense Category     41032
Offense Count        41032
Offense Type         41032
Open Data Lat        36712
Open Data Lon        36712
Open Data X          36712
Open Data Y          36712
Report Date          41032
Report Month Year    41032
dtype: int64

In [12]:
# Determine if there are any missing values in the crime data.
crime_data_df.isnull().sum()

Address              3667
Case Number             0
Crime Against           0
Neighborhood         1320
Number of Records       0
Occur Date              0
Occur Month Year        0
Occur Time              0
Offense Category        0
Offense Count           0
Offense Type            0
Open Data Lat        4320
Open Data Lon        4320
Open Data X          4320
Open Data Y          4320
Report Date             0
Report Month Year       0
dtype: int64

In [13]:
# Determine data types for the DataFrame.
crime_data_df.dtypes

Address               object
Case Number           object
Crime Against         object
Neighborhood          object
Number of Records      int64
Occur Date            object
Occur Month Year      object
Occur Time             int64
Offense Category      object
Offense Count          int64
Offense Type          object
Open Data Lat        float64
Open Data Lon        float64
Open Data X          float64
Open Data Y          float64
Report Date           object
Report Month Year     object
dtype: object

In [20]:
#drop null rows
crime_data_df_clean=crime_data_df.dropna(how='any')

In [21]:
#verify counts
crime_data_df_clean.count()

Address              36146
Case Number          36146
Crime Against        36146
Neighborhood         36146
Number of Records    36146
Occur Date           36146
Occur Month Year     36146
Occur Time           36146
Offense Category     36146
Offense Count        36146
Offense Type         36146
Open Data Lat        36146
Open Data Lon        36146
Open Data X          36146
Open Data Y          36146
Report Date          36146
Report Month Year    36146
dtype: int64

In [25]:
#check to see if there are any values with mispelled or similar values in "Offense type" using unique
crime_data_df_clean["Offense Type"].unique()

array(['False Pretenses/Swindle/Confidence Game', 'Identity Theft',
       'Credit Card/ATM Fraud', 'Embezzlement', 'Shoplifting',
       'All Other Larceny', 'Theft From Motor Vehicle',
       'Motor Vehicle Theft', 'Burglary',
       'Theft of Motor Vehicle Parts or Accessories',
       'Counterfeiting/Forgery', 'Vandalism', 'Theft From Building',
       'Robbery', 'Aggravated Assault',
       'Theft From Coin-Operated Machine or Device', 'Intimidation',
       'Simple Assault', 'Hacking/Computer Invasion',
       'Drug/Narcotic Violations', 'Pocket-Picking',
       'Stolen Property Offenses', 'Weapons Law Violations',
       'Purse-Snatching', 'Arson', 'Extortion/Blackmail', 'Prostitution',
       'Kidnapping/Abduction', 'Drug Equipment Violations',
       'Pornography/Obscene Material', 'Wire Fraud', 'Impersonation',
       'Assisting or Promoting Prostitution', 'Commercial Sex Acts',
       'Animal Cruelty', 'Welfare Fraud'], dtype=object)

In [26]:
#check to see if there are any values with mispelled or similar values in "Offense type" using .value_counts
#returns the counts of the unique values
crime_data_df_clean["Offense Type"].value_counts()

Theft From Motor Vehicle                       6947
Motor Vehicle Theft                            4689
All Other Larceny                              4558
Vandalism                                      3863
Burglary                                       2824
Shoplifting                                    2259
Identity Theft                                 1794
Simple Assault                                 1216
Drug/Narcotic Violations                       1095
Theft of Motor Vehicle Parts or Accessories    1073
Intimidation                                    900
Theft From Building                             895
False Pretenses/Swindle/Confidence Game         870
Aggravated Assault                              839
Robbery                                         608
Counterfeiting/Forgery                          448
Weapons Law Violations                          266
Credit Card/ATM Fraud                           226
Arson                                           200
Prostitution                                    145
Pocket-Picking                                   94
Purse-Snatching                                  89
Embezzlement                                     73
Stolen Property Offenses                         57
Kidnapping/Abduction                             22
Theft From Coin-Operated Machine or Device       20
Hacking/Computer Invasion                        19
Animal Cruelty                                   17
Pornography/Obscene Material                     10
Extortion/Blackmail                               8
Assisting or Promoting Prostitution               7
Drug Equipment Violations                         6
Impersonation                                     4
Wire Fraud                                        3
Commercial Sex Acts                               1
Welfare Fraud                                     1
Name: Offense Type, dtype: int64

In [28]:
#combine similar offenses
#use {} becasue it is a dictionary
crime_data_df_clean=crime_data_df_clean["Offense Type"].replace(
    {"Commercial Sex Acts ":"Prostitution","Assisting or Promoting Prostitution"})
crime_data_df_clean

SyntaxError: invalid syntax (Temp/ipykernel_27756/3434463990.py, line 4)

In [ ]:
#check to see if you combine similar offenses in
crime_data_cd_clean["Offense Types"].value_counts()